
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.assets
{
public partial class Tbasstes
{
    private readonly System.Collections.Generic.Dictionary<string, Assets> _dataMap;
    private readonly System.Collections.Generic.List<Assets> _dataList;
    
    public Tbasstes(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, Assets>();
        _dataList = new System.Collections.Generic.List<Assets>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Assets _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Assets.DeserializeAssets(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Name, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Assets> DataMap => _dataMap;
    public System.Collections.Generic.List<Assets> DataList => _dataList;

    public Assets GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Assets Get(string key) => _dataMap[key];
    public Assets this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

