
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Assets : Luban.BeanBase
{
    public Assets(JSONNode _buf) 
    {
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["ObjPath"].IsString) { throw new SerializationException(); }  ObjPath = _buf["ObjPath"]; }
        { if(!_buf["UIPath"].IsString) { throw new SerializationException(); }  UIPath = _buf["UIPath"]; }
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
    }

    public static Assets DeserializeAssets(JSONNode _buf)
    {
        return new Assets(_buf);
    }

    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 读取路径
    /// </summary>
    public readonly string ObjPath;
    public readonly string UIPath;
    public readonly int ID;
   
    public const int __ID__ = 1970626467;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "name:" + Name + ","
        + "ObjPath:" + ObjPath + ","
        + "UIPath:" + UIPath + ","
        + "ID:" + ID + ","
        + "}";
    }
}

}
